In [1]:
import pandas as pd

customers = pd.DataFrame({
    'CustomerID': [1, 2, 3, 4],
    'CustomerName': ['Alice', 'Bob', 'Charlie', 'David'],
    'City': ['London', 'Manchester', 'Leeds', 'Bristol']
})

products = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'ProductName': ['Laptop', 'Mouse', 'Keyboard'],
    'Price': [900, 25, 60]
})

orders = pd.DataFrame({
    'OrderID': [1, 2, 3, 4],
    'CustomerID': [1, 1, 2, 3],
    'ProductID': [101, 102, 103, 102],
    'Quantity': [1, 2, 1, 3]
})

df = orders.merge(customers, on = 'CustomerID', how = 'left')
df = df.merge(products, on = 'ProductID', how = 'left')

#create sale column
df['Sales'] = df['Quantity'] * df['Price']
df

,OrderID,CustomerID,ProductID,Quantity,CustomerName,City,ProductName,Price,Sales
0,1,1,101,1,Alice,London,Laptop,900,900
1,2,1,102,2,Alice,London,Mouse,25,50
2,3,2,103,1,Bob,Manchester,Keyboard,60,60
3,4,3,102,3,Charlie,Leeds,Mouse,25,75

In [6]:
###Product Analysis
product_analysis = (
    df.groupby('ProductName')
      .agg(
          TotalQuantity = ('Quantity', 'sum'),
          TotalSales = ('Sales', 'sum')
      )
      .reset_index()
)

product_analysis.sort_values(
    'TotalSales',
    ascending = False
)

  ProductName  TotalQuantity  TotalSales
1      Laptop              1         900
2       Mouse              5         125
0    Keyboard              1          60

In [7]:
###Customer Analysis
customer_analysis = (
    df.groupby('CustomerName')
    .agg(
        TotalOrders = ('OrderID', 'count'),
        TotalQuantity = ('Quantity', 'sum'),
        TotalSales = ('Sales', 'sum')
    )
    .reset_index()
)

customer_analysis.sort_values(
    'TotalSales',
    ascending = False
)

  CustomerName  TotalOrders  TotalQuantity  TotalSales
0        Alice            2              3         950
2      Charlie            1              3          75
1          Bob            1              1          60

In [8]:
###City Analysis
city_analysis = (
    df.groupby('City')
    .agg(
        TotalQuantity = ('Quantity', 'sum'),
        TotalSales = ('Sales', 'sum')
    )
    .reset_index()
)

city_analysis.sort_values(
    'TotalSales',
    ascending = False
)

         City  TotalQuantity  TotalSales
1      London              3         950
0       Leeds              3          75
2  Manchester              1          60

In [10]:
###Revenue Share
customer_analysis['RevenueShare'] = (
    customer_analysis['TotalSales'] / customer_analysis['TotalSales'].sum() * 100
)

customer_analysis.sort_values(
    'RevenueShare',
    ascending = False
)

  CustomerName  TotalOrders  TotalQuantity  TotalSales  RevenueShare
0        Alice            2              3         950     87.557604
2      Charlie            1              3          75      6.912442
1          Bob            1              1          60      5.529954